module.exports = function(sequelize, Sequelize) {
	var User;
	User = sequelize.define('User', {
		slack_id: {
			type: Sequelize.STRING,
			primaryKey: true,
			allowNull: false,
			unique: true,
			hasComment: {type: Sequelize.STRING, field: "Unique user ID generated by Slack"},
			fieldWithUnderscores: { type: Sequelize.STRING, field: "slack_id" }
		},
		slack_name: {
			type: Sequelize.STRING,
			allowNull: false,
			unique: true,
			hasComment: {type: Sequelize.STRING, field: "Username registered in Slack"},
			fieldWithUnderscores: { type: Sequelize.STRING, field: "slack_name" }
		},
		slack_role: {
			type: Sequelize.STRING,
			allowNull: false
		}
	},
	{
		tableName: 'users',
		deletedAt: 'deleted_at',
		freezeTableName: true,
		paranoid: true,
		underscored: true,
		underscoredAll: true,
		classMethods: {
			associate: function(models) {
				User.hasMany(models.User_Pokemon, {foreignKey: 'slack_id', targetKey: 'owner_id', as: 'current_owner'});
				User.hasMany(models.User_Pokemon, {foreignKey: 'slack_id', targetKey: 'caught_by', as: 'original_owner'});
			}
		}
	});

	return User;
};